### PR TITLE
Fix $ sign url escaping in WSL 2

### LINKED ISSUE #202: URL with $ does not work on WSL 2
**Bug: The opened URL is randomly missing ${word}**

Found bug when using amplify-cli https://github.com/aws-amplify/amplify-cli/issues/5664

Enviorment: 
- WSL 2
- `"open" : "^7.3.0",`

Code snippet:

```javascript
const open = require("open");

const deepLinkURL = "https://localhost/users$new?step=abc"

open(deepLinkURL, { wait: false }).catch(() => { });
```

image

Related to #170 and #171

### PR DESCRIPTION
**Pull request by CryogenicPlanet**
Closes #202

### CODE REVIEW

**Comment by tim-stasse** [comment]
Did you read the [comment on line 100](https://github.com/sindresorhus/open/blob/f3748e4f5a04a41e27034aff1eb08e8b86d01c1c/index.js#L100)?

**Comment by CryogenicPlanet** [comment]
My bad I completely missed that @tim-stasse, how would you recommend fixing #202. I wasn't able to think of a good way to escape the `$` sign, for it to work in wsl the cli should get it escaped as `\$` but javascript was automatically changing that to `$` for me

**Comment by An6r** [comment]
Does anyone have news about this one?

**Comment by sindresorhus** [comment]
@CryogenicPlanet Still interested in trying to fix this?

**Comment by CryogenicPlanet** [comment]
Hey @sindresorhus, sorry won't be able to work on this anymore. Had some other issues with WSL and now moved to linux proper so don't have WSL on hand to test a solution, even if I came up with one.

**Pull request closed without merging**
