### PR TITLE
Fix issue #236. Additional option "hiddenTerminal"

### PR DESCRIPTION
**Pull request by kykint**

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't add options lightly. Please explain why the behavior happens in the first place. If there's a way to solve this without an option, I would prefer that.

**Comment by qm3ster** [comment]
Sure seemed like this 👉 https://github.com/sindresorhus/open/pull/235 👈  option in the call to powershell was added lightly 😉
What happens is that running `powershell.exe –WindowStyle Hidden` from a terminal, where a new Powershell window wouldn't spawn anyway, instead reconfigures the window of the host to making it invisible. The same happens even if nodejs is a middleman.

This is a very confusing behavior, and for a while both the person that asked for my help with this issue and the creator of https://github.com/sindresorhus/open/issues/236 thought the host is being terminated.

**Comment by sindresorhus** [comment]
Alright, PR welcome to revert that commit then.

**Comment by qm3ster** [comment]
But then a PowerShell window will pop up and scare the users when used from a graphical application binary.

**Comment by met583** [comment]
what steps should i take to prevent the terminal from being hidden?  Fix (lookup)?

**Comment by qm3ster** [comment]
@met583 you can use `"open": "8.0.2"` (not `"open": "^8.0.2"` or `"open": "8.0.5"`) until this is merged.

**Comment by met583** [comment]
> @ met583 puoi usare `"open": "8.0.2"`(not `"open": "^8.0.2"`or `"open": "8.0.5"`) fino a quando non viene unito.
> Puoi ottenerlo con `npm i -E open@8.0.2`( `-E`per "esatto")

Thanks, where should I enter that command?  In the cdm "open" is not recognized as an internal or external command.  How do I proceed?

**Pull request closed without merging**
