### PR TITLE
feat: Prefer powershell core over powershell windows

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
This PR check does the user has new Powershell core, if it uses that, in case if it's not then it fallbacks to the old Windows tied PowerShell

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why does it matter which PowerShell it uses?

**Comment by sindresorhus** [comment]
But that doesn't really matter in our case. We just use it to execute a single command. I can think of more downsides: potentially breaking changes, differing behavior, etc.

**Comment by ShreyasJejurkar** [comment]
> potentially breaking changes, differing behavior

Powershell Core is the same as the old Powershell but with a better-performing runtime and the same feature parity as the old one. 

And also if we don't find a new PowerShell, we are anyway to fallback to the old one to avoid any breaking things.

**Comment by sindresorhus** [comment]
> Powershell Core is the same as the old Powershell but with a better-performing runtime and the same feature parity as the old one.

Minor performance differences does not really matter much here. The slow part is launching the apps, not executing the command. And you haven't really provided any evidence of performance improvements for this specific case.

> And also if we don't find a new PowerShell, we are anyway to fallback to the old one to avoid any breaking things.

That's not the kind of breaking changes I'm talking about. The core one is a moving target. It may be identical today, but in 2 years, it may break some feature or subtly change some behavior.

**Comment by sindresorhus** [comment]
I'm going to pass on this as the benefit does not outweigh the risk.

**Pull request closed without merging**
