### PR TITLE
Don't use empty catch blocks please

### PR DESCRIPTION
**Pull request by FilipParyz**
I suppose a change to not use an empty catch block and at least print an error message.

### CODE REVIEW

**Comment by FilipParyz** [comment]
obraz
While using [PKG](https://www.npmjs.com/package/pkg) to package my node.js app using 'open' module, I'm running into a problem as shown on the screenshot. I'm new to node.js and js in general so I'd love some feedback if there's some workaround.
I still think that a change should be made here though, as empty catch blocks aren't a great practice.

**Comment by sindresorhus** [comment]
Packages should not log directly to the console.

**Comment by sindresorhus** [comment]
> I still think that a change should be made here though, as empty catch blocks aren't a great practice.

If you read the code, you'll see that not catching the error is intended.

**Comment by sindresorhus** [comment]
Your problem is either a too old Node.js version or a JS parser not being able to handle the syntax here. Neither are problems with this package.

**Pull request closed without merging**
